deployment:
  tasks:
    - export DEPLOYPATH=/home/arwoccxa/.softaculous/demo.toanthaybao.com
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ "$DEPLOYPATH"/
